Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "forwarded_port", guest: 5000, host: 5000
  config.vm.network "forwarded_port", guest: 5001, host: 5001
  config.vm.synced_folder "D:\\KNU_FIT\\crossPlatformRogramming\\lr5\\lr5\\bin\\Release\\net6.0\\publish", "/home/vagrant/lr5-server"
end