Vagrant.configure("2") do |config|
  config.vm.box = "yzgyyang/macOS-10.14"
  # Synced folder не підтримується під Mac OS X
  config.vm.synced_folder ".", "/vagrant", :disabled => true
  # Temporary fix for annoying "Replace key" issue
  config.ssh.insert_key = false
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    # Fix "hfsmountedmacintosh hdon deviceroot_device" issue
    vb.customize ["modifyvm", :id, "--cpuidset", "1", "000206a7", "02100800", "1fbae3bf", "bfebfbff"]
    # Some more hacks for device recognition
    vb.customize ["setextradata", :id, "VBoxInternal/Devices/efi/0/Config/DmiSystemProduct", "MacBookPro13,3"]
    vb.customize ["setextradata", :id, "VBoxInternal/Devices/efi/0/Config/DmiSystemVersion", "1.0"]
    vb.customize ["setextradata", :id, "VBoxInternal/Devices/efi/0/Config/DmiBoardProduct", "Iloveapple"]
    vb.customize ["setextradata", :id, "VBoxInternal/Devices/smc/0/Config/DeviceKey", "нашійроботіза словамизахищеніпорожнинидостатньо(c)Apple Computer Inc"]
  end
end